#!/usr/bin/env bash
# 上游漂移检查：比对 Noelle-Libraries-Pack@main 中本库的文件夹与本地 pin，
# 漂移则 upsert [upstream] issue；一致则关闭（daily）/ 巡检（monthly）。
#
# 依赖: gh, jq, base64。环境变量:
#   FACTS    upstream facts json（默认 .github/upstream-facts.json）
#   RUN_MODE daily|monthly（由 workflow 判定触发源传入）
#
# 标题英文，正文先英文整段、后中文整段（与 monthly-update-check 一致）。
set -euo pipefail

: "${FACTS:?.github/upstream-facts.json}"
: "${RUN_MODE:?RUN_MODE required (daily|monthly)}"
FACTS="$(cd "$(dirname "$FACTS")" && pwd -P)/$(basename "$FACTS")"

REPO=$(jq -r '.upstream.repo' "$FACTS")
BRANCH=$(jq -r '.upstream.branch' "$FACTS")
PATHV=$(jq -r '.upstream.path' "$FACTS")
REF=$(jq -r '.upstream.ref' "$FACTS")
TREE=$(jq -r '.upstream.tree_sha' "$FACTS")
LIB_VERSION=$(jq -r '.upstream.lib_version' "$FACTS")
ENGINE_VER=$(jq -r '.upstream.engine_ver' "$FACTS")
LIB_DEPS=$(jq -c '.upstream.dependencies // []' "$FACTS")
PREFIX="[upstream]"
REPO_SELF="${GITHUB_REPOSITORY:-Bli-AIk/unknown}"

CI_NOTE_EN="Generated by CI: daily drift check at 02:00 UTC; monthly fallback on the 2nd at 02:30 UTC; manual dispatch available. Recompute pins with the commands in UPSTREAM.md."
CI_NOTE_ZH="本提醒由 CI 自动生成：每日 02:00 UTC 检测漂移；每月 2 号 02:30 UTC（东八 10:30）兜底巡检；可手动触发。pin 重算命令见 UPSTREAM.md。"

log() { echo "[$(date -u +%FT%TZ)] $*"; }

upsert_issue() {
  local title="$1" body="$2"
  mapfile -t existing < <(gh issue list --state open --limit 100 --json number,title \
    --jq ".[] | select(.title | startswith(\"$PREFIX\")) | .number" || true)
  if [[ ${#existing[@]} -gt 0 ]]; then
    local first="${existing[0]}"
    for ((i = 1; i < ${#existing[@]}; i++)); do
      gh issue close "${existing[$i]}" >/dev/null 2>&1 || true
    done
    gh issue edit "$first" --title "$title" --body "$body" >/dev/null 2>&1 || true
  else
    gh issue create --title "$title" --body "$body" >/dev/null 2>&1 || true
  fi
}

close_all() {
  local nums
  nums="$(gh issue list --state open --limit 100 --json number,title \
    --jq ".[] | select(.title | startswith(\"$PREFIX\")) | .number" || true)"
  for n in $nums; do
    gh issue close "$n" >/dev/null 2>&1 || true
  done
}

fetch_json_field() {
  # $1 = path under repo, $2 = jq filter (on the decoded file)
  gh api "repos/${REPO}/contents/${PATHV}/${1}?ref=${BRANCH}" --jq '.content' 2>/dev/null \
    | base64 -d 2>/dev/null | jq -r "$2" 2>/dev/null || true
}

check_additional_sources() {
  local source_name source_repo source_branch tree_json path expected actual drift=""
  while IFS=$'\t' read -r source_name source_repo source_branch; do
    tree_json="$(gh api "repos/${source_repo}/git/trees/${source_branch}?recursive=1" 2>/dev/null || true)"
    while IFS=$'\t' read -r path expected; do
      actual="$(printf '%s' "$tree_json" | jq -r --arg path "$path" \
        '.tree[] | select(.path == $path) | .sha' 2>/dev/null | head -1 || true)"
      actual="${actual:-unknown}"
      if [[ "$actual" != "$expected" ]]; then
        drift="$drift source(${source_name}:${path} ${expected} -> ${actual})"
      fi
    done < <(jq -r --arg source "$source_name" \
      '.additional_sources[$source].blobs | to_entries[] | [.key, .value] | @tsv' "$FACTS")
  done < <(jq -r \
    '(.additional_sources // {}) | to_entries[] | [.key, .value.repo, .value.branch] | @tsv' "$FACTS")
  printf '%s' "$drift"
}

main() {
  local now_ref now_tree now_lib now_engine now_deps additional_drift primary_drift drift_target
  now_ref="$(gh api "repos/${REPO}/commits/${BRANCH}" --jq '.sha' 2>/dev/null || true)"
  now_tree="$(gh api "repos/${REPO}/git/trees/${BRANCH}?recursive=1" \
    --jq ".tree[] | select(.path==\"${PATHV}\") | .sha" 2>/dev/null || true)"
  now_lib="$(fetch_json_field "lib.json" '.version')"
  now_engine="$(fetch_json_field "lib.json" '.engineVer')"
  now_deps="$(fetch_json_field "lib.json" '[.dependencies // []]')"
  # lib.json is JSONC; strip comments if the plain request didn't work
  if [[ -z "$now_lib" || -z "$now_engine" ]]; then
    raw="$(gh api "repos/${REPO}/contents/${PATHV}/lib.json?ref=${BRANCH}" --jq '.content' 2>/dev/null | base64 -d 2>/dev/null || true)"
    now_lib="$(echo "$raw" | grep -oE '"version"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | grep -oE '"[^"]*"$' | tr -d '"')"
    now_engine="$(echo "$raw" | grep -oE '"engineVer"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | grep -oE '"[^"]*"$' | tr -d '"')"
  fi

  # normalize
  now_lib="${now_lib:-unknown}"; now_engine="${now_engine:-unknown}"; now_tree="${now_tree:-unknown}"
  now_deps_msg=""
  if [[ -n "$now_deps" && "$now_deps" != "[]" ]]; then
    now_deps_msg=", dependencies=$(echo "$now_deps" | tr -d '[:space:]')"
  fi

  log "repo=${REPO_SELF} path=${PATHV} run=${RUN_MODE} tree=${now_tree} lib=${now_lib} engine=${now_engine}"

  local drift=""
  [[ "$now_tree" != "$TREE" ]] && drift="$drift tree($TREE -> $now_tree)"
  [[ "$now_lib" != "$LIB_VERSION" ]] && drift="$drift version($LIB_VERSION -> $now_lib)"
  [[ "$now_engine" != "$ENGINE_VER" ]] && drift="$drift engineVer($ENGINE_VER -> $now_engine)"
  primary_drift="$drift"
  additional_drift="$(check_additional_sources)"
  drift="$drift$additional_drift"
  [[ -n "$additional_drift" ]] && log "additional source drift:${additional_drift}"

  if [[ -z "$drift" ]]; then
    if [[ "$RUN_MODE" == "monthly" ]]; then
      upsert_issue "${PREFIX} ${now_ref:0:7} Monthly check: in sync" \
"**Upstream drift check — in sync**

- ${REPO}@${BRANCH}, ${PATHV}: tree \`${now_tree}\`, lib ${now_lib}, engineVer ${now_engine}${now_deps_msg}
- Pinned facts match (\`${FACTS}\`). Nothing to do.

${CI_NOTE_EN}

---

**上游漂移检查——无变化**

- ${REPO}@${BRANCH}，${PATHV}：tree \`${now_tree}\`，lib ${now_lib}，engineVer ${now_engine}${now_deps_msg}
- 与 pin（\`${FACTS}\`）一致，无需处理。

${CI_NOTE_ZH}"
    else
      close_all
    fi
    return 0
  fi

  local commits
  commits="$(gh api "repos/${REPO}/commits?path=${PATHV}&sha=${BRANCH}&per_page=10" \
    --jq '.[] | "\(.sha[0:7]) \(.commit.author.date[0:10]) \(.commit.message | split("\n")[0])"' 2>/dev/null || echo "(unable to list commits)")"

  drift_target="$PATHV"
  if [[ -z "$primary_drift" && -n "$additional_drift" ]]; then
    drift_target="additional sources"
  fi

  upsert_issue "${PREFIX} ${now_ref:0:7} Upstream drift: ${drift_target}" \
"**Upstream drift detected**

- Primary source: **${REPO}** @ \`${BRANCH}\`, path \`${PATHV}\`, pinned at \`${REF}\`.
- Additional source blobs are tracked in \`${FACTS}\` and are included in the drift signals below.
- Pinned: tree \`${TREE}\`, lib ${LIB_VERSION}, engineVer ${ENGINE_VER}
- Found: tree \`${now_tree}\`, lib ${now_lib}, engineVer ${now_engine}${now_deps_msg}
- Drift signals:${drift}

Recent upstream commits touching the primary path:

\`\`\`
${commits}
\`\`\`

Suggested actions:
1. Review the primary diff: \`gh repo diff ${REPO} ${REF} -- ${PATHV}\`; compare any additional-source paths named above against their pinned blobs.
2. Port relevant fixes onto this fork (cherry-pick style, add \`Co-authored-by\`).
3. After review, update the pins in \`${FACTS}\` and note it in \`UPSTREAM.md\`.
4. **Prefer sending the fixes upstream as a PR** (\`${REPO}\`) — upstream backport beats fork-local drift.

${CI_NOTE_EN}

---

**检测到上游漂移**

- 主来源：**${REPO}** @ \`${BRANCH}\`，路径 \`${PATHV}\`，pin 为 \`${REF}\`。
- 额外来源 blob 记录在 \`${FACTS}\` 中，也会出现在下方漂移项里。
- Pin 值：tree \`${TREE}\`，lib ${LIB_VERSION}，engineVer ${ENGINE_VER}
- 当前值：tree \`${now_tree}\`，lib ${now_lib}，engineVer ${now_engine}${now_deps_msg}
- 漂移项：${drift}

上游最近触及主路径的提交：

\`\`\`
${commits}
\`\`\`

建议动作：
1. 审阅主路径差异：\`gh repo diff ${REPO} ${REF} -- ${PATHV}\`；额外来源请按上方列出的路径与其 pin blob 对比。
2. 把相关修复移植到本 fork（带 \`Co-authored-by\` 署名）。
3. 复核后更新 \`${FACTS}\` 中的 pin，并在 \`UPSTREAM.md\` 记录。
4. **优先把修复作为 PR 回捐上游**（\`${REPO}\`）——回捐优于 fork 本地漂移。

${CI_NOTE_ZH}"
}

main
